import rich_click as click
from click import Context
from rich import print  # type: ignore

from .action import action
from .autocompletion import autocompletion

# configure rich-click
click.rich_click.SHOW_ARGUMENTS = True
click.rich_click.MAX_WIDTH = 80
CONTEXT_SETTINGS = dict(help_option_names=["-h", "--help"])


def purge_ci_toolkit_caches() -> None:
    """
    Deletes cache directories used by the toolkit to store temporary files.
    """
    from python_ci_toolkit.environment.paths import _ci_temp_files_root_directory

    print(f":boom: Purging cache directory '{_ci_temp_files_root_directory}'...")

    from python_ci_toolkit.git import delete_git_repo
    delete_git_repo(_ci_temp_files_root_directory)  # <- we use this to delete the caches because it can handle deleting Git repos which may be present inside

    print(":white_check_mark: Caches successfully purged!")


@click.group(context_settings=CONTEXT_SETTINGS, invoke_without_command=True, no_args_is_help=True)
@click.version_option()
@click.option("--debug",
              is_flag=True,
              help="Enable debug logging.")
@click.option("--purge-caches",
              is_flag=True,
              help="Delete any temporary files generated by the toolkit from the system's cache directory. "
                   "This includes cloned action repos and any files generated by running CI actions.")
@click.pass_context
def cli(ctx: Context, debug: bool = False, purge_caches: bool = False) -> None:
    """
    Tool to streamline the use of Python scripts in CI/CD automation.
    """

    # initialize logging
    from python_ci_toolkit.logging import configure_ci_logging
    configure_ci_logging("DEBUG" if debug else "INFO")

    # purge caches if necessary
    if purge_caches:
        purge_ci_toolkit_caches()
        ctx.exit(0)


# Register CLI commands
cli.add_command(autocompletion)
cli.add_command(action)

if __name__ == '__main__':
    cli()
