definitions:
  anchors:
    - &use_python_ci_runner_image # step settings to use python-ci-runner Docker image
      oidc: true
      services:
        - docker
      image:
        name: 755432789552.dkr.ecr.eu-west-1.amazonaws.com/pyci/runner:latest
        aws:
          oidc-role: $AWS_OIDC_ROLE_ARN
  steps:
    - step: &handle_semantic_version_development
        <<: *use_python_ci_runner_image
        name: Handle semantic version (development)
        script:
          - python-ci-action generate_development_semver_from_git:develop
          - python-ci-action push_committed_changes_and_tags_to_git:develop
    - step: &handle_semantic_version_release
        <<: *use_python_ci_runner_image
        name: Handle semantic version (release)
        script:
          - python-ci-action generate_release_semver_from_git:develop
          - python-ci-action push_committed_changes_and_tags_to_git:develop
    - step: &release_poetry_package
        <<: *use_python_ci_runner_image
        name: Build and publish Poetry package
        script:
          - python-ci-action setup_aws_cli
          - python-ci-action build_poetry_package
          - python-ci-action publish_poetry_package
    - step: &update_python_ci_containers
        <<: *use_python_ci_runner_image
        name: Update self dependency in python-ci-containers
        script:
          - python-ci-action update_dependency_in_python_ci_containers:local

pipelines:
  branches:
    develop:
      - step: *handle_semantic_version_development
    main:
      - step: *handle_semantic_version_release
      - step: *update_python_ci_containers
  tags:
    'v*':
      - step: *release_poetry_package
