[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "python-ci-toolkit"
version = "0.10.2-dev"
description = "A collection of tools for building CI Python scripts used by PyCI"
authors = [ "PyCI <hello@pyci.dev>",]

[tool.poetry.dependencies]
python = "^3.10"
rich = ">=1"
semver = ">=2"
toml = ">=0.10"
GitPython = ">=3.1"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
python-ci-action = "python_ci_toolkit.actions:cli"
