"""
Environment-variable names used by the action process protocol.
"""

PYCI_ACTION_OUTPUT_ENV_VAR = "PYCI_ACTION_OUTPUT"
PYCI_ACTION_STACK_ENV_VAR = "PYCI_ACTION_STACK"
PYCI_INTERNAL_ACTION_RESULT_ENV_VAR = "PYCI_INTERNAL_ACTION_RESULT"
PYCI_INTERNAL_ACTION_RUN_ID_ENV_VAR = "PYCI_INTERNAL_ACTION_RUN_ID"
PYCI_INTERNAL_EVENT_TOKEN_ENV_VAR = "PYCI_INTERNAL_EVENT_TOKEN"
PYCI_INTERNAL_LOG_LEVEL_ENV_VAR = "PYCI_INTERNAL_LOG_LEVEL"
PYCI_INTERNAL_ROOT_COLUMNS_ENV_VAR = "PYCI_INTERNAL_ROOT_COLUMNS"
PYCI_INTERNAL_ROOT_LINES_ENV_VAR = "PYCI_INTERNAL_ROOT_LINES"
PYCI_INTERNAL_UV_RUNTIME_ARGUMENTS_ENV_VAR = "PYCI_INTERNAL_UV_RUNTIME_ARGUMENTS"
