"""
Functions for working with common paths used in CI scripts.
"""

import logging
import os

logger = logging.getLogger(__name__)


def _ensure_ci_temp_files_directories_exist() -> None:
    """
    Ensures that the directories for temporary CI files exist.
    """
    from .internal import ci_temp_files_root_directory, ci_temp_files_projects_root_directory, ci_temp_files_shared_directory
    os.makedirs(ci_temp_files_root_directory, exist_ok=True)
    os.makedirs(ci_temp_files_shared_directory, exist_ok=True)
    os.makedirs(ci_temp_files_projects_root_directory, exist_ok=True)


_ensure_ci_temp_files_directories_exist()


def purge_temporary_files() -> None:
    """
    Purges all temporary files generated by the CI toolkit.
    """
    # delete all temporary directories by deleting the root one
    from ...git import delete_git_repo  # <- we use this to delete the caches because it can handle deleting Git repos which may be present inside
    from .internal import ci_temp_files_root_directory
    delete_git_repo(ci_temp_files_root_directory)

    # create new empty temporary directories
    _ensure_ci_temp_files_directories_exist()
