from pathlib import Path

from ...environment import ci_platform
from ...shell import run_shell_command


class CiPaths:

    def __init__(self):
        # determine if we're inside a Git repo
        result = run_shell_command("git rev-parse --show-toplevel")
        self._git_repo_root = Path(result.output_stripped) if result.is_successful else None

    @property
    def project_root(self) -> Path:
        """
        Absolute path to the current project's root directory.

        Notes:
            This is guaranteed to be accurate in cloud CI environments (e.g. Bitbucket Pipelines).

            When on a local machine, it will look for the outermost Git repository's root relative to the current working directory;
            if no Git repo is found, current working directory will be assumed to be the project's root.
        """
        return ci_platform.get_ci_project_root()

    @property
    def ci_files_directory(self) -> Path:
        """
        Absolute path to the directory containing CI files in the current project.

        Notes:
            This directory can be used to store scripts and configuration files related to the given project's CI workflows.
        """
        return self.project_root / Path(".ci")

    @property
    def temp_files_directory(self) -> Path:
        """
        Absolute path to the location of temporary files generated by CI logic.

        Notes:
            This directory can and should be used for storing any temporary files generated by CI logic.

            This directory is unique per CI project, so there is no risk of temporary CI files clashing with those from another CI project on the same machine.
            Name of this directory is tied to the SHA of the first commit in this repo's repository; this means the project's temp directory persists even if the path to the
            project's directory changes.

            If current CI project root is not a Git repo, this returns a shared temp directory.
        """
        from .internal import ci_temp_files_projects_root_directory, ci_temp_files_shared_directory

        if self._git_repo_root:
            # when inside a CI project repo, generate the path based on the initial commit's short SHA
            first_commit_sha = run_shell_command("git rev-list --max-parents=0 HEAD", cwd=self.project_root).output_stripped
            first_commit_sha_short = first_commit_sha[:7]
            directory = ci_temp_files_projects_root_directory / first_commit_sha_short
        else:
            # when outside any repo, point to the shared temp directory
            directory = ci_temp_files_shared_directory

        # ensure that directory exists
        if not directory.exists():
            directory.mkdir(parents=True, exist_ok=True)

        return directory


ci_paths = CiPaths()
