[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[project]
name = "epic-dummy-pyproject-file-to-test-version-parsing"
version = "1.0.0-test"
description = "A collection of tools for building CI Python scripts used by PyCI"
requires-python = ">=3.10"
authors = [
    { name = "PyCI", email = "hello@pyci.dev" },
]
dependencies = [
    "hopes>=2.0",
    "prayers>=9.1",
    "pure-determination==1.0.0-dev",
]
