[build-system]
requires = [ "poetry-core>=1.0.0",]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "epic-dummy-pyproject-file-to-test-version-parsing"
version = "1.0.0-test"
description = "A collection of tools for building CI Python scripts used by PyCI"
authors = [ "PyCI <hello@pyci.dev>",]

[tool.poetry.dependencies]
python = "^3.8"
hopes = ">=2.0"
prayers = ">=9.1"
pure-determination = "1.0.0-dev"

[tool.poetry.dev-dependencies]
fuck = "ass"
