name: "Handle development version"

on:
  workflow_dispatch:
  pull_request_target:
    types:
      - closed

jobs:
  handle-semver-development:
    if: github.event.pull_request.merged == true
    name: Handle development version
    uses: pyci/.github-private/.github/workflows/handle-semver-development.yml@main
    secrets: inherit
    permissions:
      contents: write
      packages: read
