name: "Handle semver (development)"

on:
  push:
    branches:
      - 'develop'

env:
  PYTHON_CI_ACTIONS_GIT_REPO_URL: ${{ secrets.PYTHON_CI_ACTIONS_GIT_REPO_URL }}
  PYTHON_CI_ACTIONS_SSH_PRIVATE_KEY: ${{ secrets.PYTHON_CI_ACTIONS_SSH_PRIVATE_KEY }}
  PYTHON_CI_PUSH_SSH_PRIVATE_KEY: ${{ secrets.PYTHON_CI_PUSH_SSH_PRIVATE_KEY }}
  PYTHON_CI_GIT_USER_EMAIL: ${{ vars.PYTHON_CI_GIT_USER_EMAIL }}
  PYTHON_CI_GIT_USER_NAME: ${{ vars.PYTHON_CI_GIT_USER_NAME }}

jobs:
  build-dockers-and-push:
    name: Handle semver (development)
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/pyci/ci-runner:latest"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: pyci print_environment_info
      - run: pyci set_git_identity
      - run: pyci generate_semver_development_from_git@action/semvers
      - run: pyci push_changes_to_git_through_ssh