name: "Publish new version"

on:
  push:
    tags:
      - 'v*'

jobs:
  publish-poetry-package:
    name: Publish Poetry package
    uses: pyci/.github/.github/workflows/publish-poetry-package.yml@main
    secrets: inherit
  update-python-ci-runner:
    name: Update self dependency in Python CI Runner
    needs: publish-poetry-package
#    uses: ./.github/workflows/update-python-ci-runner.yml
