name: "Update Python CI Runner"

on: workflow_call

env:
  AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
  AWS_CI_ACCESS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
  AWS_CI_SECRET_ACCESS_KEY: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}
  PYTHON_CI_ACTIONS_GIT_REPO_URL: ${{ secrets.PYTHON_CI_ACTIONS_GIT_REPO_URL }}
  PYTHON_CI_ACTIONS_SSH_PRIVATE_KEY: ${{ secrets.PYTHON_CI_ACTIONS_SSH_PRIVATE_KEY }}
  PYTHON_CI_PUSH_SSH_PRIVATE_KEY: ${{ secrets.PYTHON_CI_PUSH_SSH_PRIVATE_KEY }}

jobs:
  update-python-ci-runner:
    name: Update self dependency in Python CI Runner
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    container:
      image: "ghcr.io/pyci/ci-runner:latest"
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - run: pyci update_dependency_in_python_ci_containers@local